from typing import Optional, Literal
from pydantic import BaseModel, Field
from langgraph.graph import MessagesState

class JobAgentState(MessagesState):
    # Input
    raw_url: Optional[str] = None
    raw_prompt: Optional[str] = None

    # Parsed intent
    intent: Optional[Literal["full_application", "unrelated"]] = None

    # Navigation & Classification Engine
    current_url: Optional[str] = None
    navigation_history: list[str] = Field(default_factory=list)
    page_type: Optional[Literal["listing", "description", "application_form", "unknown"]] = None

    # Job details
    job_url: str = ""
    apply_url: Optional[str] = None
    chosen_job_url: Optional[str] = None # Used when routing from a listing page
    extracted_job_details: dict = Field(default_factory=dict) # Used to store structured data like benefits, requirements, etc.
    job_title: Optional[str] = None
    job_description: Optional[str] = None
    company_name: Optional[str] = None

    # Form fields found on apply page
    form_fields: list[dict] = Field(default_factory=list)
    # e.g. [{"name": "email", "type": "text", "required": True}, ...]

    form_metadata: dict = Field(default_factory=dict)
    # e.g. {"contains_captcha": True, "primary_submit_selector": "button#submit"}

    # CV
    cv_path: Optional[str] = None  # path to generated PDF
    cv_data: dict = Field(default_factory=dict)
    # Normalized CV data (from DOCX or JSON) — used by map_fields and cv_builder.
    # Guaranteed keys: name, email, phone, summary, skills (list), experience (list of dict),
    # education (list of dict), projects (list of dict), certifications (list of str), extra (dict)

    # Control flow
    needs_cv: bool = False
    form_ready: bool = False
    applied: bool = False

    # Form data mapping (plan generated by LLM)
    form_data: dict[str, dict] = Field(default_factory=dict)
    # e.g. {"email_selector": {"action": "type", "value": "user@example.com"}}

    # Final message to user
    notification: Optional[str] = None
    error: Optional[str] = None